### ISSUE TITLE
Please invite me to the community

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [web3community/support#28]
### Name

Kaiwalya Koparkar

### Discord Username (if applicable)

Kaiwalya Koparkar#0747

### Additional Context

Hey, I would like to be a part of this community

**Comment by shuklaritvik06** [comment]
Welcome to the community @kaiwalyakoparkar ! Very Happy to have you in the community! :)

**Comment by KukretiShubham** [comment]
Welcome @kaiwalyakoparkar . Glad you are part of community
