### ISSUE TITLE
Please invite me to the community

### ISSUE THREAD

**Issue by zeeshanmahar007** [web3community/support#5]
### Name

Mahar

### Discord Username (if applicable)

zeeshanmahar#9894

### Additional Context

Know about this community on LinkedIn. Working on new technologies and want to learn This web 3 technology and teach others.

**Comment by vinzvinci** [comment]
Thanks, I will fix the bug later. The actions failed. I'll ping you when it's done

**Comment by vinzvinci** [comment]
Hello, thank you for waiting. Please create new issues again for invitation :)
